export const theme = {
  colors: {
    background: 'var(--color-background)',
    foreground: 'var(--color-foreground)',
    primary: 'var(--color-primary)',
    primaryForeground: 'var(--color-primary-foreground)',
    secondary: 'var(--color-secondary)',
    secondaryForeground: 'var(--color-secondary-foreground)',
    accent: 'var(--color-accent)',
    accentForeground: 'var(--color-accent-foreground)',
    muted: 'var(--color-muted)',
    mutedForeground: 'var(--color-muted-foreground)',
    destructive: 'var(--color-destructive)',
    destructiveForeground: 'var(--color-destructive-foreground)',
    card: 'var(--color-card)',
    cardForeground: 'var(--color-card-foreground)',
    popover: 'var(--color-popover)',
    popoverForeground: 'var(--color-popover-foreground)',
    border: 'var(--color-border)',
    input: 'var(--color-input)',
    ring: 'var(--color-ring)',
    bgBase: 'var(--color-bg-base)',
    bgSurface: 'var(--color-bg-surface)',
    bgElevated: 'var(--color-bg-elevated)',
    bgSubtle: 'var(--color-bg-subtle)',
    borderDefault: 'var(--color-border-default)',
    borderSubtle: 'var(--color-border-subtle)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    textFaint: 'var(--color-text-faint)',
    accentPrimary: 'var(--color-accent-primary)',
    accentPrimaryDim: 'var(--color-accent-primary-dim)',
    accentAi: 'var(--color-accent-ai)',
    accentAiText: 'var(--color-accent-ai-text)',
    stateError: 'var(--color-state-error)',
    stateSuccess: 'var(--color-state-success)',
    stateWarning: 'var(--color-state-warning)',
  },
  font: {
    sans: 'var(--font-inter), sans-serif',
    mono: 'var(--font-fira-code), monospace',
    heading: 'var(--font-inter), sans-serif',
  },
  typography: {
    caption: '0.75rem',
    body: '1rem',
    heading: '1.5rem',
  },
  spacing: {
    xs: 'var(--space-xs)',
    sm: 'var(--space-sm)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
  },
  radii: {
    input: 'var(--radius-lg)',
    panel: 'var(--radius-xl)',
    overlay: 'var(--radius-2xl)',
  },
  breakpoints: {
    mobile: '320px',
    tablet: '768px',
    desktop: '1024px',
  },
} as const;

export type Theme = typeof theme;
